#spring.application.name=jobSearch
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/JobSearchdb
#spring.dataSource.username=postgres
#spring.dataSource.password=Priyanshu@1265
#spring.dataSource.driver-class-name=org.postgresql.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#server.port=8080

spring.application.name=jobSearch

spring.datasource.url=jdbc:postgresql://jobdb-instance.cfg0aqys6ica.ap-south-1.rds.amazonaws.com:5432/jobsearchdb?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Priyanshu1265
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Configuration - HTTPS Enabled
server.port=8443
server.ssl.key-store=classpath:jobsearch.p12
server.ssl.key-store-password=Priyanshu1265
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=jobsearch